export const siteConfig = {
  name: 'Free UPSC Preparation',
  shortName: 'FUP',
  domain: 'https://freeupsc.online',
  telegramUrl: 'https://t.me/+VK2Zgo5UrrY0MDg1',
  email: 'hello@freeupsc.online',
  description: 'A calm, structured and completely free study companion for serious UPSC aspirants.',
}

export const watchlistCategories = [
  { id: 'gs', label: 'General Studies', short: 'GS', description: 'Conceptual clarity for the papers that shape your rank.' },
  { id: 'current-affairs', label: 'Current Affairs', short: 'CA', description: 'Context-rich explainers for a better understanding of the news.' },
  { id: 'ncert', label: 'NCERT Foundation', short: 'NC', description: 'The essential school texts, read with an exam lens.' },
  { id: 'optional', label: 'Optional Subjects', short: 'OP', description: 'A thoughtful starting point for choosing and mastering your optional.' },
]

export type WatchlistResource = {
  subject: string
  source: string
  playlistId: string
  firstVideoId: string
  playlistUrl: string
  firstVideoUrl: string
  firstVideoTitle: string
  videos?: PlaylistVideo[]
}

export type PlaylistVideo = {
  title: string
  videoId?: string
  index?: number
}

export const gsWatchlist: WatchlistResource[] = [
  { subject: 'Polity', source: 'M. Laxmikanth, chapter-wise', playlistId: 'PLMjnMh7f2NYa9OS9MEGAaPfATt5oDXLtz', firstVideoId: 'OSc8pBacMwk', playlistUrl: 'https://youtube.com/playlist?list=PLMjnMh7f2NYa9OS9MEGAaPfATt5oDXLtz&si=3_oQj6ra3lZeJtef', firstVideoUrl: 'https://youtu.be/OSc8pBacMwk?si=A7nRbV0zO19nPFaZ', firstVideoTitle: 'Chapter-1 Historical Background | Indian Polity by M. Laxmikanth | UPSC 2026', videos: [
    { title: 'Chapter-1 Historical Background', videoId: 'OSc8pBacMwk' },
    { title: 'Chapter-2 Making of the Constitution', videoId: 'ZQPYg696yD8' },
    { title: 'Chapter-4 Salient Features of the Constitution', videoId: 'rvFWnxTRu2w' },
    { title: 'Chapter-5 Preamble of the Constitution', videoId: 'ItdxMGbzHxA' },
    { title: 'Chapter-6 Union and its Territory', videoId: 'hwU0ODSPi5U' },
    { title: 'Chapter-7 Citizenship', videoId: 'ytaigja2T84' },
    { title: 'Chapter-8 Fundamental Rights - Part 1', videoId: 'ukbBYk11OcE' },
    { title: 'Chapter-8 Fundamental Rights - Part 2', videoId: '6sfHG9g9NpI' },
    { title: 'Chapter-8 Fundamental Rights - Part 3', videoId: 'hXSrZA8byz8' },
    { title: 'Fundamental Rights - Revision + PYQs & Practice Questions', videoId: 'sJHgT4zdtlc' },
    { title: 'Chapter-9 Directive Principles of State Policy', videoId: '_alOUx6-xx4' },
    { title: 'Chapter-10 Fundamental Duties', videoId: '7ZJetv0bVrA' },
    { title: 'Chapter-11 Amendment of the Constitution', videoId: 'LFTYB3WsemE' },
    { title: 'Chapter-12 Basic Structure of the Constitution', videoId: 'M5YzRRHq35c' },
    { title: 'Chapter-13 & 14 Parliamentary and Federal System', videoId: 'e40eRDOsNJE' },
    { title: 'Chapter-15 Centre-State Relations - Part 1', videoId: 'Z9E3ac8Tmko' },
    { title: 'Chapter-15 Part 2 & Chapter-16 Inter-State Relations', videoId: 'OXW2RRr_9mw' },
    { title: 'Chapter-17 Emergency Provisions - Part 1', videoId: 'uMV4Zol_MUo' },
    { title: 'Chapter-17 Emergency Provisions - Part 2', videoId: 'O4PSraBF7ig' },
    { title: 'Chapter-18 President of India', videoId: 'WozIPxczBMc' },
    { title: 'Chapter-19 Vice President of India', videoId: '31fonlVQn4I' },
    { title: 'Chapter-20 Prime Minister of India', videoId: 'Nt3X3x0Rvjg' },
    { title: 'Chapter-21 Central Council of Ministers', videoId: '6YBpYu4bPWo' },
    { title: 'Chapter-22 Cabinet Committees', videoId: 'rpMNU_7HahQ' },
    { title: 'Chapter-23 Parliament - Part 1', videoId: '1uH50DVO-yE' },
    { title: 'Chapter-23 Parliament - Part 2', videoId: 'j6_df1bWGbg' },
    { title: 'Chapter-23 Parliament - Part 3', videoId: 'B3YT_ojxaqM' },
    { title: 'Chapter-24 Parliamentary Committees', videoId: 'PqPyesS71Uo' },
    { title: 'Polity Laxmikanth - Revision + Previous Year Questions', videoId: 'C0-M6pOoIvo' },
    { title: 'Chapter-26 Supreme Court', videoId: 'WiREy1mDRUU' },
    { title: 'Chapter-27 Judicial Review', videoId: 'yH3HSnIrEtU' },
    { title: 'Chapter-30 Governor', index: 32 },
    { title: 'Chapter-31 Chief Minister', videoId: 'jImB1LVLoOQ' },
    { title: 'Chapter-32 State Council of Ministers', videoId: '85ypoV_Ijn4' },
    { title: 'Chapter-33 State Legislature', videoId: 'HlzaRaCW8pg' },
    { title: 'Chapter-34 High Court', videoId: 'EZDQGxO6ogk' },
    { title: 'Chapter-35 Subordinate Courts', index: 37 },
    { title: 'Chapter-39 Panchayati Raj', videoId: 'O7CQ8dnwTaU' },
  ] },
  { subject: 'Modern History', source: 'Bipin Chandra by Rinku Singh', playlistId: 'PLNxxHbb6Q8MXZFzTSETU_QXs6WRP3ttXG', firstVideoId: 'giekFtljym0', playlistUrl: 'https://youtube.com/playlist?list=PLNxxHbb6Q8MXZFzTSETU_QXs6WRP3ttXG&si=FioJKvVW3Frju-aM', firstVideoUrl: 'https://www.youtube.com/live/giekFtljym0?si=wC6NmtrWjwnhPUz3', firstVideoTitle: 'Chapter 2 - Lecture 1 | Modern Indian History by Bipin Chandra', videos: [
    { title: 'Chapter 2 - Lecture 1', videoId: 'giekFtljym0' },
    { title: 'Chapter 2 - Lecture 2', index: 2 },
    { title: 'Chapter 2 - Lecture 3', videoId: 'mcWpPSqaWRY' },
    { title: 'Chapter 3 - Lecture 1', videoId: 'zpRIBOdRrwk' },
    { title: 'Chapter 3 - Lecture 2', videoId: 'vyaNfV7NSq8' },
    { title: 'Chapter 4 - Lecture 1', index: 6 },
    { title: 'Chapter 4 - Lecture 2', videoId: 'SSLOXzHqwwM' },
    { title: 'Chapter 4 - Lecture 3', index: 8 },
    { title: 'Chapter 4 - Lecture 4', index: 9 },
    { title: 'Chapter 5 - Complete Summary', videoId: 'HmFc0CEdVPU' },
    { title: 'Chapter 6 - Complete Summary', videoId: 'yEOh9opiob4' },
    { title: 'Chapter 6 - Part 2', videoId: 'XeZXwvQlSl0' },
    { title: 'Chapter 7 - Part 1', index: 13 },
    { title: 'Chapter 8 - Part 1', videoId: 'JNJzS_h5sNg' },
    { title: 'Chapter 8 - Part 2', index: 15 },
    { title: 'Chapter 9 - Nationalist Movement in India', index: 16 },
    { title: 'Chapter 10 - Religious and Social Reforms: After 1858', videoId: 'sQhWHP6HgXs' },
  ] },
  { subject: 'Geography', source: 'PMF IAS', playlistId: 'PLfhUF7AO5ZR16jjRQmHEGYw_Xi1RGsrzq', firstVideoId: 'b0ooZWBQWRk', playlistUrl: 'https://youtube.com/playlist?list=PLfhUF7AO5ZR16jjRQmHEGYw_Xi1RGsrzq&si=miTuJ2d2EVO-l1Ad', firstVideoUrl: 'https://youtu.be/b0ooZWBQWRk?si=fyJU2ZErbPMk-HQ3', firstVideoTitle: 'L1-Study Guide for Geography-Booklist, Previous Questions Analysis Part 1', videos: [
    { title: 'L1-Study Guide for Geography-Booklist, Previous Questions Analysis Part 1', videoId: 'b0ooZWBQWRk' },
    { title: 'L2-Study Guide for Geography-Booklist, Previous Questions Analysis Part 2', videoId: 'vQuJd7H9ZLg' },
    { title: 'G1-Astronomy: The Universe, Big Bang, Red Shift, Blue Shift', videoId: '-QA5smJnT-k' },
    { title: 'G2-Astronomy: Solar System, Nebular Theory, Sun Structure, Magnetosphere, Aurora', videoId: '8KvWWDu81Ns' },
    { title: "G3-Earth's Interior: Seismic Waves - Primary, Secondary, Surface Waves", videoId: 'fy-9eXg_7H8' },
    { title: "G4-Earth's Interior: Shadow Zone of S & P Waves, Crust, Core, Mantle", videoId: 'dkdZnD5ck-I' },
    { title: 'G5-Earth Movements: Endogenic, Diastrophism, Epeirogenic, Subsidence & Upliftment', videoId: 's2lVo9yLkQs' },
    { title: 'G6-Earth Movements: Denudation, Weathering - Physical, Chemical, Biological', videoId: '0VUo_AX4Qac' },
    { title: 'G7-Tectonics: Continental Drift Theory and Evidences', videoId: 'ysGYLrkrxmo' },
    { title: 'G8-Tectonics: Sea Floor Spreading, Paleomagnetism', videoId: 'w3xaX6gkecg' },
    { title: 'G9-Tectonics: Plate Tectonics, Major and Minor Crustal Plates', videoId: '8hMD52kUhRk' },
    { title: 'G10-Comparison: Continental Drift, Sea Floor Spreading, Plate Tectonics', videoId: 'K3nPnJffGFM' },
    { title: 'G11-Tectonics: Divergent Plate Boundary and East African Rift Valley', videoId: 'ssrmdGtcoNA' },
    { title: 'G12-Tectonics: Convergent Boundary and Island Archipelagos', videoId: '0TmnbdOglDs' },
    { title: 'G13-Tectonics: Fold Mountains, Himalayas, Rockies', videoId: 'puOaCr93ORI' },
    { title: 'G14-Tectonics: Types of Mountains - Fold, Block, Volcanic & Residual', videoId: 'WUwrvmFQE38' },
    { title: 'G15-Rocks: Igneous, Sedimentary, Metamorphic, Rock Cycle', videoId: 'EcDv2u9y2vM' },
    { title: 'G16-Volcanism: Active, Dormant, Extinct, Composite and Shield Volcanoes', videoId: 'xnIYk8vRmXc' },
    { title: 'G17-Volcanism: Types and Positive & Negative Effects', videoId: 'Em0GQw-Pc6w' },
    { title: 'G18-Volcanic Landforms: Batholith, Laccolith, Sill, Dyke, Caldera Lake', videoId: '6GUYQMx1GiY' },
    { title: 'G19-Springs, Geysers, Distribution of Volcanoes and Hotspot Volcanism', videoId: 'QIMQSwiHCDw' },
    { title: 'G20-Earthquakes: Causes and Mechanism', videoId: 'eYms_bVDnOw' },
    { title: 'G21-Tsunami: Causes, Normal Waves vs Tsunami Waves, 2004 Indian Ocean', videoId: 'V78KKmkPtbM' },
    { title: 'G22-Fluvial Erosional Landforms: Downcutting, Lateral Erosion, Meanders, Terraces', videoId: 'OHZEtlraGA8' },
    { title: 'G23-Fluvial Depositional Landforms and Drainage Patterns', videoId: '_j8bAvUF130' },
    { title: 'G24-Glacial, Marine & Arid Landforms', videoId: 'rclSWD-sL0U' },
    { title: 'C1-Latitudes & Longitudes: Day and Night, Seasons, GMT, IST, Date Line', videoId: 'DuTy6zFRl4s' },
    { title: 'C2-Atmosphere: Troposphere, Stratosphere, Ozone, Ionosphere', videoId: 'QiZ1ie6F80M' },
    { title: 'C3-Temperature Distribution: Heat Budget, Heat Balance, Albedo', videoId: 'JO7hUIMvb88' },
    { title: 'C4-Adiabatic Lapse Rate and Latent Heat of Condensation', videoId: 'OiAPNpdD4Z4' },
    { title: 'C5-Pressure Belts, Permanent Winds and Coriolis Force', videoId: 'B8pKQYViJYY' },
    { title: 'C6-Pressure Belts: Trade Winds, Westerlies, Horse Latitudes, Deserts', videoId: 'nEsKyz0Cc6w' },
    { title: 'C7-Periodic Winds: Land & Sea Breeze, Mountain & Valley Breeze, Monsoon', videoId: 'kMISOalQfpQ' },
    { title: 'C8-Ocean Currents: Gulf Stream, North Atlantic Drift, Benguela, Kuroshio, Oyashio', videoId: '6-tGwHO1o7w' },
    { title: 'C9-Temperature Inversion: Advectional, Air Drainage, Surface Type', videoId: '3CGhmAFFhiI' },
    { title: 'C10-Jet Streams and Impact on Weather', videoId: 'JRrM6Inrhn4' },
    { title: 'C11-Air Masses, Clouds and Fronts: Stationary, Cold, Warm', videoId: 'gDcjqvr13Sg' },
    { title: 'C12-Temperate Cyclones and Occluded Front', videoId: 'rKb-qcKmnpU' },
    { title: 'C13-Humidity, Relative Humidity, Dew Point, Evaporation, Condensation', videoId: 'tRLdN3FfLZM' },
    { title: 'C14-Photochemical Smog, Dew, Frost, Fog, Mist and Sulfurous Smog', videoId: 'yoO_xDAm2mI' },
    { title: 'C15-Thunderstorms, Tornadoes, Convectional, Orographic and Frontal Rainfall', videoId: 'T9cKm8T_DD0' },
    { title: 'C16-Tornado, Waterspout, Hail Formation, Thunder and Lightning, Downbursts', videoId: 'ys-h4fuOwBI' },
    { title: 'C17-El Nino, Walker Cell, Indian Ocean Dipole, El Nino Modoki, La Nina', videoId: 'jcFo1i5zzHc' },
    { title: 'C18-Tropical Cyclones: Conditions, Origin, Development, Distribution', videoId: 'gDf2Z18nAD8' },
    { title: 'C19-Tropical Cyclones: Storm Surge, Storm Tide, Category 1-5', videoId: '-JyB8q9e-XU' },
    { title: 'C20-Cyclones in Bay of Bengal vs Arabian Sea and Southwest Monsoon', videoId: 'myrTAxCEAHE' },
    { title: 'C21-Tropical Cyclone and Temperate Cyclone: Comparison', videoId: 'cMyqHk_8SkI' },
    { title: 'C22-Polar Vortex, Ozone Hole, Ozone Depletion, Polar Stratospheric Clouds', videoId: '5zkp_JN5_Vk' },
    { title: 'C23-Rainforest Climate, Koeppen Scheme, Environmental Threats, Resource Curse', videoId: 'X94PCwczGKM' },
    { title: 'C24-Tropical Savanna Climate: Vegetation and Economy', videoId: 'OSCH3Dt2O2M' },
    { title: 'C25-Tropical Monsoon Climate and Climatic Regions', videoId: 'oXAl5NLX0L8' },
    { title: 'C26-Desert Climate: Hot Deserts, Mid-Latitude Deserts, Minerals', videoId: 'rQQsSbuStf4' },
    { title: 'C27-Steppe Climate, Temperate Continental Climate, Prairies', videoId: 'P-2zYZ52VTg' },
    { title: 'C28-Mediterranean Climate and Warm Temperate West Coast Climate', videoId: 'fuHSuHBV66o' },
    { title: 'C29-Warm Temperate Eastern Margin Climate: China, Gulf, Natal Type', videoId: 'TNUDDFlFMXI' },
    { title: 'C30-British Type Climate: Cool Temperate Western Margin Climate', videoId: 'QQC44Cnfx3Q' },
    { title: 'C31-Laurentian Climate: Cool Temperate Eastern Marine Climate', videoId: 'aj6_rMPyKMQ' },
    { title: 'C32-Taiga Climate, Lumbering in Taiga, Tundra Climate', videoId: 'J1009uujtAI' },
    { title: 'C33-Climatic Regions Revision', videoId: 'xDeDsIZZ5Ig' },
    { title: 'O1-Ocean Relief: Oceanography for UPSC Prelims and Mains', videoId: 'MXKNTK86RWQ' },
    { title: 'O2-Temperature Distribution of Oceans and Ocean Currents', videoId: 'OnmGtQPtZ7c' },
  ] },
  { subject: 'Economy', source: 'Mrunal Patel', playlistId: 'PLAMBum9_RkuMn_Zo2BrpUlVIl7rRxtu9X', firstVideoId: 'AjQcbHYpEHE', playlistUrl: 'https://youtube.com/playlist?list=PLAMBum9_RkuMn_Zo2BrpUlVIl7rRxtu9X&si=UgBpv2qysQW_rKT9', firstVideoUrl: 'https://youtu.be/AjQcbHYpEHE?si=MRFZz4TKlVwzdcKc', firstVideoTitle: '[Economy] incremental CRR (i-CRR): RBI ko chadhi nayi sanak, REPO-CRR se nahi kyon nahi bujhi unki tarang', videos: [
    { title: '[Economy] incremental CRR (i-CRR), REPO and CRR explained', videoId: 'AjQcbHYpEHE' },
    { title: '[Economy] ADR, GDR, Direct Listing at IFSC, Public Ltd vs Pvt Ltd, IPO-FPO, FDI-FPI', videoId: 'qMdkSkSCv9E' },
    { title: '[Economy] TOTEX Model, RDSS Scheme, Smart Electricity Meter, PPP', videoId: 'sAoKcYBtW3s' },
    { title: '[Economy] Mains-storming using Prelim Facts: Budget Financial Health', videoId: 'uRKep3M1iTE' },
    { title: '[Economy] PM-PRANAM Scheme to reduce urea and fertiliser use', videoId: 'kRF2fEaXirY' },
    { title: '[Mains Pipudi/GSM2] Budget approval in India vs USA', videoId: '0MfVYxU1P-w' },
    { title: '[Economy] Recession, Depression and Stagflation explained', videoId: '4PpRZEXSPV0' },
    { title: '[Economy] Subjective, Relative and Absolute Poverty Line', videoId: 'RhCIBXbmE_I' },
    { title: '[K3G Economy] EPFO Subscriber, Captive Investor and Adani Stock', videoId: 'NElnDLNP1iQ' },
    { title: 'Economy Overheating, Front Loading Stimulus, QE and Fed Tapering', videoId: '-VkEwnjB8uU' },
    { title: '[Economy] SWAMIH Fund AIF Category 2 for unfinished housing projects', videoId: 'SQK79drgGlM' },
    { title: '[Economy] Short-Selling in Share Market and Adani-Hindenburg', videoId: 'Ck0x3d23UkA' },
    { title: 'Budget and Economic Survey: How to prepare for UPSC', videoId: 'y29EQk7k8F0' },
    { title: '[Economy] SEBI NSE Co-location Scam vs SAT Order and Trading', videoId: 'jouNhG5VW8c' },
    { title: '[Economy] AT1 Bond Investors, Yes Bank Scam, Bombay HC and Basel', videoId: 'Ne4mh6IJPQQ' },
    { title: '[Economy] RBI Dividend to Government and Fiscal Position', videoId: 'R1_s2R_LOmw' },
    { title: '[Economy] Inflation Target Failure and RBI Governor', videoId: 'nLuQKAJsrBc' },
    { title: '[Economy] Reverse Currency War, Fed Tapering, Rupee Exchange Rate and Exports', videoId: 'OFj-oz-DeQI' },
    { title: '[Economy] Yield Inversion and Upcoming Recession', videoId: 'BDACRJAo-48' },
    { title: '[Economy] Soft Landing vs Hard Landing, Monetary Policy and GDP', videoId: 'tz6DE50CQZQ' },
    { title: '[IR/Diplomacy] Rupee-Ruble Agreement, De-Dollarisation and India-Japan Meet', videoId: 'i8Cif3kCsr0' },
    { title: '[Economy Current] Dollar Swap, NLMC and EPFO Interest', videoId: '4KUQzYit4O4' },
    { title: '[Economy Current] UPI 123PAY, DigiSaathi, UPI Limit, NPCI and NACH', videoId: 'tdTBIEXwEE0' },
    { title: '[Economy] PFRDA-MARS, SEBI Chief, GDP Growth Downgrade and IPCC Report', videoId: 'bnOfoY7q8Z0' },
    { title: 'RBI Monetary Policy, Variable Repo, VRRR, CRR-ASISO, e-RUPI, TReDS-NACH', videoId: 'q-GNbExdTlA' },
  ] },
]

export type Article = { title: string; excerpt: string; category: string; date: string; readTime: string; slug: string }

export const articles: Article[] = [
  { title: 'The calm way to begin your UPSC preparation', excerpt: 'A practical framework for turning a large syllabus into small, repeatable study days.', category: 'Strategy', date: 'Coming soon', readTime: '6 min read', slug: 'calm-way-to-begin' },
  { title: 'How to read the newspaper for UPSC', excerpt: 'Move beyond highlighting. Learn how to extract issues, arguments and useful examples.', category: 'Current Affairs', date: 'Coming soon', readTime: '8 min read', slug: 'read-newspaper-for-upsc' },
  { title: 'NCERTs: what to read, and what to skip', excerpt: 'A clean first-pass reading list for building a strong foundation without losing momentum.', category: 'Foundation', date: 'Coming soon', readTime: '5 min read', slug: 'ncert-reading-list' },
]

export const faqs = [
  ['Is FUP completely free?', 'Yes. Every resource we publish is designed to be accessible without a paid batch or subscription.'],
  ['What does FUP provide?', 'Curated study material, newspaper guidance, NCERT direction, a useful YouTube watchlist and practical preparation notes.'],
  ['Is this for beginners only?', 'No. We are building the library for every stage, from first reading to revision and answer-writing.'],
  ['Where will new resources be shared?', 'Join the Telegram community to receive fresh resources, updates and weekly study prompts.'],
]
